== Xen - Déploiement d'une machine virtuelle NetBSD (HVM)

[WARNING]
======================================================================
Certaines instructions processeurs sont requises pour pouvoir démarrer
une machine virtuelle en mode HVM. VirtualBox ne semble pas être
compatible (du moins avec NetBSD) pour utiliser cette fonctionnalité,
il est donc préférable d'utiliser un serveur physique non virtualisé.

Si vous voulez tout de même tester cette fonctionnalité vous devrez
utiliser un émulateur ou un hyperviseur capable de faire des machines
virtuelles imbriquées. `qemu` permet de configurer explicitement les
options du CPU.

[sh]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
qemu-system-x86_64 -cpu qemu64,+vmx -smp cpus=2 -m 1024M \
  -hda $hdd
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

ou avec `kvm` (sous linux)

[sh]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
kvm -cpu qemu64,+vmx -smp cpus=2 -m 1024M \
  -hda $hdd
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Pour améliorer les performances, il est possible d'utiliser certains
drivers. Attention, NetBSD et le kernel XEN3_DOM0 ne supporte pas en
natif les drivers `virtio`, vous serez obligé de reconfigurer votre
kernel.

[sh]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
qemu-system-x86_64 -cpu qemu64,+vmx -smp cpus=2 \
                   -m 1024M \
		   -device if=virtio,file=$hdd
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Pour voir les options disponibles et supportées par votre version de
`qemu` vous pouvez utiliser `qemu-system-x86_64 -cpu help` ou
`qemu-system-x86_64 -device help`.
======================================================================

.Création de la configuration de la VM (/xen/etc/netbsd-hvm.cfg)
[txt]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
name="netbsd-hvm"
builder="hvm"
disk=["/xen/netbsd/disk.raw","/xen/netbsd/install.iso,,,devtype=cdrom"]
boot="d"
vif=["bridge=bridge0"]
memory=256
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

.Récupération de l'installeur
[sh]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cd /xen/netbsd
REPO=http://ftp.fr.netbsd.org/pub/NetBSD
ftp -o install.iso ${REPO}/NetBSD-6.1.5/amd64/installation/cdrom/boot.iso
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

.Initialisation du container (disque dur virtuel)
[sh]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mkdir -p /xen/netbsd
cd /xen/netbsd

# création d'une image disque vierge de 512MB
dd if=/dev/zero of=disk.raw bs=1m count=512
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

.Initialisation du bridge (ifconfig)
[sh]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ifconfig bridge0 create
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

.Déploiement de la VM
[sh]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
xl create /xen/etc/netbsd-hvm.cfg
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

.Accès à la VM (`ctrl-]` pour revenir sur l'hôte)
[sh]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
xl console netbsd-hvm
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

.Arrêt de la VM
[sh]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
xl destroy netbsd-hvm
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

