== Unix - Qu'est-ce qu'un processus?

Un processus est un programme en cours d'exécution. Il possède un état
définis par le kernel (en cours de création, en cours d'exécution, en
sommeil, arrêté ou zombifié). Lors du lancement, il lui est aussi
attribué un identifiant unique (PID). Vu qu'un processus est un
programme exécuté, il possède des attributs lié à l'utilisateur et au
groupe qui l'a exécuté par exemple.

Un système Unix peut lancer plusieurs processus, chacun possédant sa
propre zone mémoire et isolé de tous les autres processus. Les
processus sont concurrents, ils peuvent s'exécuter en parallèle. C'est
le kernel qui détient le pouvoir d'organiser quel processus sera
exécuté avant l'autre, ordre basé sur un ordonnanceur (scheduler).

[sh]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
# exécution de la commande sleep en tâche de fond
sleep 100 &

# la variable spéciale $! permet d'afficher le PID de la dernière
# commande mis en tache de fond
echo $!

# on affiche les informations du processus fonctionnant en tâche de
# fond
ps -aux -p $!
procstat $!
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

